import { analyseSpendingBehaviour } from '../engine/behaviourEngine'
import { formatINR } from '../utils/currency'

const palette = ['#356f9b', '#6d9879', '#d49748', '#a86a5e', '#7992a4']
export function Cashflow({ data }) {
  const income = data.expectedIncome.reduce((sum, item) => sum + Number(item.amount), 0)
  const expenses = data.upcomingExpenses.reduce((sum, item) => sum + Number(item.amount), 0)
  const behaviour = analyseSpendingBehaviour(data.spendingHistory)
  const categories = Object.entries(behaviour.categories).sort((a,b) => b[1] - a[1])
  const max = Math.max(...categories.map(([,value]) => value), 1)
  return <section className="ms-page"><div className="ms-page-heading"><div><p className="ms-kicker"><i/> CASHFLOW</p><h1>Where your next 30 days are going.</h1><p>Analytics are derived from the demo transaction history and planned commitments.</p></div></div><div className="ms-cash-summary"><article><span>Expected income</span><b>{formatINR(income)}</b><small>Next 30 days</small></article><article><span>Planned expenses</span><b>{formatINR(expenses)}</b><small>Recurring and upcoming</small></article><article><span>Net cashflow</span><b className={income - expenses < 0 ? 'negative' : ''}>{formatINR(income - expenses)}</b><small>Before a new decision</small></article></div><div className="ms-cash-grid"><section className="ms-cash-card"><p className="ms-kicker"><i/> INCOME VS EXPENSES</p><h2>Cashflow balance</h2><div className="ms-bars"><div><span>Income</span><i><em className="income" style={{width:`${Math.min(100, income / Math.max(income, expenses) * 100)}%`}}/></i><b>{formatINR(income)}</b></div><div><span>Expenses</span><i><em className="expense" style={{width:`${Math.min(100, expenses / Math.max(income, expenses) * 100)}%`}}/></i><b>{formatINR(expenses)}</b></div></div></section><section className="ms-cash-card"><p className="ms-kicker"><i/> SPENDING BREAKDOWN</p><h2>Where spending concentrates</h2><div className="ms-category-list">{categories.length ? categories.map(([name,value],index) => <div key={name}><span style={{background:palette[index % palette.length]}}/><b>{name}</b><i style={{width:`${value/max*100}%`}}/><strong>{formatINR(value)}</strong></div>) : <p className="ms-empty-copy">No transaction history available yet.</p>}</div></section></div><div className="ms-cash-grid"><section className="ms-cash-card"><p className="ms-kicker"><i/> RECURRING COMMITMENTS</p><h2>Scheduled expenses</h2><div className="ms-upcoming-list">{data.upcomingExpenses.map(item => <div key={item.id}><span>Day {item.daysUntil}</span><b>{item.name}</b><strong>{formatINR(item.amount)}</strong></div>)}</div></section><section className="ms-cash-card"><p className="ms-kicker"><i/> DECISION DNA</p><h2>What the data says</h2><div className="ms-dna-list"><p><b>Weekend spending</b><span>{behaviour.weekendLift}% higher than weekdays</span></p><p><b>Largest category</b><span>{behaviour.topCategory} · {formatINR(behaviour.topSpend)}</span></p><p><b>Typical comfort buffer</b><span>{formatINR(data.assumptions.safetyReserve)}</span></p><p><b>Commitment load</b><span>{formatINR(expenses)} in the next 30 days</span></p></div></section></div></section>
}
