import { Plus, Save } from 'lucide-react'
import { defaultDemoData } from '../data/demoData'

const number = value => Math.max(0, Number(value || 0))
export function SettingsPanel({ data, setData, onReset }) {
  const update = (key, value) => setData(current => ({ ...current, [key]: number(value) }))
  const updateAssumption = (key, value) => setData(current => ({ ...current, assumptions: { ...current.assumptions, [key]: number(value) } }))
  const updateGoal = (key, value) => setData(current => ({ ...current, goals: current.goals.map((goal, index) => index ? goal : { ...goal, [key]: key === 'name' ? value : number(value) }) }))
  const updateEvent = (type, id, key, value) => setData(current => ({ ...current, [type]: current[type].map(item => item.id === id ? { ...item, [key]: key === 'name' ? value : number(value) } : item) }))
  return <section className="ms-page-card ms-settings"><div className="ms-page-heading"><div><p className="ms-kicker"><i/> EDITABLE DEMO DATA</p><h1>Make this demo yours.</h1><p>These values are stored locally and update every calculation immediately.</p></div><button className="ms-outline" onClick={onReset}><Save size={15}/>Reset demo data</button></div><div className="ms-settings-grid"><article><h2>Financial position</h2><label>Current balance<input type="number" min="0" value={data.currentBalance} onChange={event => update('currentBalance', event.target.value)}/></label><h3>Expected income</h3>{data.expectedIncome.map(item => <div className="ms-edit-row" key={item.id}><input value={item.name} onChange={event => updateEvent('expectedIncome', item.id, 'name', event.target.value)}/><input type="number" value={item.amount} onChange={event => updateEvent('expectedIncome', item.id, 'amount', event.target.value)}/><input aria-label={`${item.name} day`} type="number" value={item.daysUntil} onChange={event => updateEvent('expectedIncome', item.id, 'daysUntil', event.target.value)}/></div>)}</article><article><h2>Upcoming expenses</h2>{data.upcomingExpenses.map(item => <div className="ms-edit-row" key={item.id}><input value={item.name} onChange={event => updateEvent('upcomingExpenses', item.id, 'name', event.target.value)}/><input type="number" value={item.amount} onChange={event => updateEvent('upcomingExpenses', item.id, 'amount', event.target.value)}/><input aria-label={`${item.name} day`} type="number" value={item.daysUntil} onChange={event => updateEvent('upcomingExpenses', item.id, 'daysUntil', event.target.value)}/></div>)}<small>Rows are name · amount · days from today</small></article><article><h2>Goal</h2><label>Goal name<input value={data.goals?.[0]?.name || ''} onChange={event => updateGoal('name', event.target.value)}/></label><label>Target amount<input type="number" min="0" value={data.goals?.[0]?.target || 0} onChange={event => updateGoal('target', event.target.value)}/></label><label>Already saved<input type="number" min="0" value={data.goals?.[0]?.currentSaved || 0} onChange={event => updateGoal('currentSaved', event.target.value)}/></label></article><article><h2>Scenario assumptions</h2><label>Emergency amount<input type="number" min="0" value={data.assumptions.emergencyAmount} onChange={event => updateAssumption('emergencyAmount', event.target.value)}/></label><label>Alternative price<input type="number" min="0" value={data.assumptions.alternativeAmount} onChange={event => updateAssumption('alternativeAmount', event.target.value)}/></label><label>EMI down payment<input type="number" min="0" value={data.assumptions.emiDownPayment} onChange={event => updateAssumption('emiDownPayment', event.target.value)}/></label><label>EMI monthly payment<input type="number" min="0" value={data.assumptions.emiMonthlyPayment} onChange={event => updateAssumption('emiMonthlyPayment', event.target.value)}/></label></article></div></section>
}
